import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400"], // Add the desired font weights as needed
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import './globals.css'
import { Navbar02 } from '@/components/ui/shadcn-io/navbar-02'
import Footer from '@/components/ui/footer'

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen flex flex-col font-poppins">
          <header className="w-full">
            <Navbar02 />
          </header>

          <main className="flex-1 w-full">
            {children}
          </main>

          <Footer />
        </div>
      </body>
    </html>
  )
}
